
SECRET_KEY = 'XxxxXXxxXXXXxxXXXXXXXX'

MAX_CONTENT_LENGTH = 8 * 2048 * 2048 # 8 MB file upload max

# CKEDITOR
CKEDITOR_SERVE_LOCAL = True
CKEDITOR_ENABLE_CSRF = True
CKEDITOR_FILE_UPLOADER = 'main.upload'


DEBUG_TB_INTERCEPT_REDIRECTS = False
SESSION_PROTECTION = 'strong'
'''
MAIL_SERVER = private.MAIL_SERVER
MAIL_PORT = private.MAIL_PORT
MAIL_USE_SSL = private.MAIL_USE_SSL
MAIL_USE_TLS = private.MAIL_USE_TLS
MAIL_USERNAME = private.MAIL_USERNAME
MAIL_PASSWORD = private.MAIL_PASSWORD
MAIL_DEBUG = private.DEBUG
MAIL_DEFAULT_SENDER = private.MAIL_DEFAULT_SENDER

ADMIN_EMAIL = private.ADMIN_EMAIL
STARTING_ADMINS = private.STARTING_ADMINS
STARTING_ADMIN_PASS = private.STARTING_ADMIN_PASS
'''